### ISSUE TITLE
early planning

### ISSUE THREAD

**Issue by katieannemills** [GRIFFINCollaboration/griffin-website#1]
We'll be pulling together a website for GRIFFIN in the coming weeks - now would be a good time for a discussion of design aesthetic. Please post links to websites you like the look of, or websites that have individual elements you like.

cc @AdamGarnsworthy

**Comment by katieannemills** [comment]
ping! working on this this week, let me know any requests or content (text? pictures? other stuff?) people would like to see baked in.

**Comment by AdamGarnsworthy** [comment]
trshare.TRIUMF.ca/~garns/GRIFFIN
Is the basic content. Plus the toolkit of web apps we developed for griffin with the addition of the one developed by Jenna.

**Comment by r3dunlop** [comment]
I think it would be nice to have a very basic angular correlation applet in there, this would be part of the toolkit. All it would have to do is use the average efficiency for each detector and apply user specified “a” values. We could then quickly determine whether it’s possible to do angular correlation measurements and how many events we would need to see a pattern. This came up during the Cd experiments. I’m not sure if this is the place to post that request, or if we have a toolkit area to make such requests.

**Comment by katieannemills** [comment]
@AdamGarnsworthy roger that

@r3dunlop great idea! I think @SmithJK has just such a thing under development, which will be built into the toolkit and linked from here. As for other requests for new tools, sure, post them here; if they're accepted they'll get their own repos where we can have more detailed discussion, but this is as good a place as any to start the conversation (in their own threads :).

**Comment by SmithJK** [comment]
Can we include a web interface for loading a calibration to the ODB? We've written a script that will do this from the command line, but it's much more user friendly to have a web page where you upload a calibration file that is read and then implemented in the ODB. I suggest standardizing to the GRSISort calibration file style, detailed here: https://github.com/GRIFFINCollaboration/GRSISort/wiki/CalFiles.

**Comment by r3dunlop** [comment]
I _think_ we already have a cal->odb script. Not sure the shape it’s in as I believe it was a “we need it right now” script. But if you need something like this for this service it can be used.

**Comment by AdamGarnsworthy** [comment]
I agree a webpage would be good for this task but that should be a custom page or link from the midas page. This main public face page can include web tools for exp planning or data analysis but not Daq things. This page can have a link to the midas page though which is where someone should find all that stuff. This public page will not be password protected. All daq stuff should be (at least at the very basic level that we do it)

**Comment by SmithJK** [comment]
@AdamGarnsworthy Good call. I'll move the suggestion over to the Dashboard.

**Comment by katieannemills** [comment]
sounds good - closing here, cont'd in https://github.com/GRIFFINCollaboration/griffinMarkII/issues/52
