### ISSUE TITLE
Angular correlation tool

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/griffin-website#2]
I've been working on a basic angular correlation tool already.  See https://github.com/SmithJK/AngularCorrelationUtility.

Other development ideas:
- A page where four of the five quantities are set and the fifth (any spin or mixing ratio) is allowed to vary. The result would be a plot of possible a2 and a4 values, similar to the ellipse that Andrew has drawn before.
- A page where you could input a2 and a4 values and get a list of possible spin/mixing ratio combinations that would produce those values. A further extension would allow for the inclusion of uncertainties of a2 and a4 and produce 2D plots that would show (for each possible combination of three spins), the ranges of mixing ratios possible.
- A page specifically showing what an experimental angular correlation spectrum would look like. User inputs the a2 and a4 values and a number of counts to produce an angular correlation plot. "Data" for plot could be sampled from a simulated data set. Re-submitting the value would produce a different sampling of the data (so you could re-submit 10 times and get an idea of the possible variance in your data depending on the number of events).

I'm working on a bug in the webpage right now. After that gets fixed, I'll transfer it to GRIFFINCollaboration ownership.

@r3dunlop @AndrewMac1

**Comment by AndrewMac1** [comment]
This sounds really good, one thing that may be nice to add (depending on the difficulty) is a plot of a2 and a4 versus the mixing ratio. This way we could see the sharpness in the changes of a2/a4 and can allow us to check that our error bars on the ellipse plot made actually make sense and that we correctly assign the error on the mixing ratios. 

----- Original Message -----

**Comment by SmithJK** [comment]
I can see this being relatively easy to include for varying a single mixing
ratio, but a bit more difficult for varying two. For varying a single one,
it would fit in well on the "fix four, vary one" page.

**Comment by katieannemills** [comment]
@SmithJK any feature that boils down to calculations and plots is very doable, I'd be happy to help unless you're keen to do it yourself. Can you point me at a review of the relevant physics?

BTW, do please add a LICENSE file to your tool before transferring ownership; any open source license (MIT, BSD, GNU, apache...) is fine, and feel free to maintain copyright yourself - not too concerned with the details as long as they are explicitly stated whatever they are, preferably by the original author.

**Comment by SmithJK** [comment]
I am happy to pass this project off to you. Most of the physics functions are taken directly from the C++ functions that Evan wrote for our Geant angular correlations package. There's a decent quick description of the physics here, along with some references: https://github.com/GRIFFINCollaboration/Geant4GammaGammaAngularCorrelations10.01.p01/blob/master/README.pdf

Yes, I can include a LICENSE file.

**Comment by katieannemills** [comment]
OK cool, sounds good! I'll add this to my to-dos.

**Comment by katieannemills** [comment]
@SmithJK - can you write me a 1 sentence description of this tool to go [here](http://griffincollaboration.github.io/griffin-website/toolkit.html)? Thanks!

**Comment by SmithJK** [comment]
How about:

GRIFFIN's increased gamma-gamma efficiency and 52 unique opening angles
make it a prime tool for measuring gamma-gamma angular correlations; the
Angular Correlation calculator displays the expected angular correlation
based on the spins and mixing ratios involved in a gamma-gamma cascade.

Obviously, this will need to be expanded later (hopefully).

**Comment by katieannemills** [comment]
thanks! Let me know what you'd like to do for expansion; the physics page has some examples of in depth articles, and we could certainly add something like that if you like.

**Comment by katieannemills** [comment]
@AndrewMac1 I just pushed your plot of a2 and a4 as a function of mixing ratios here: http://griffincollaboration.github.io/AngularCorrelationUtility/ - let me know if they make sense.

**Comment by AndrewMac1** [comment]
Looks awesome! The values seem to make sense as far as I can tell, I looked at about 5 I knew off hand and each looked good. I also like that I get a pop up message if I do some stupid and try to choose something out of scope or that doesn't make sense. Just a few things to think about, would it be difficult to add projections of the mixing ratio plots? Just to see a2 (or a4) versus mixing ratio, especially for the cases when there is only one mixing ratio like a 2->2->0 for example. Also, another feature that would be useful but again it depends on the difficulty is if we could plot the ellipses of a2/a4. This would be more difficult as it would have to calculate a few of them and store the a2/a4 values somehow, but it would be really useful for simulations in helping to decide what range of mixing ratios to test. Let me know what you think if it is possible and again looks great!

----- Original Message -----

**Comment by katieannemills** [comment]
Yep, @SmithJK asked for those projections too - they're there now, let me know if they don't look right.

Re: ellipses: it's not impossible, but we do need to move on to the rest of the toolkit soon; I can fiddle with this for today, but it'll have to go on the backburner after that.

**Comment by katieannemills** [comment]
How about something like this for iso surfaces:
![screen shot 2015-12-08 at 9 50 09 am](https://cloud.githubusercontent.com/assets/1896943/11663463/35e0129e-9d91-11e5-95ec-9b06e12eb84f.png)

Of course the tooltip still provides exact values. This isn't live yet - let me know if it's what people want, and I can push it to production.

cc @AndrewMac1 @SmithJK

**Comment by AndrewMac1** [comment]
I guess I am just a bit confused as to what we will get from the surfaces. Would it be possible to expand the range of the a2/a4 verses mixing ratio x-axis values so we can see the convergence for large mixing ratio values? Currently when you scroll the plotted values end at the original plotted image. Is it possible to make the axis scale to the users wishes? Also could you use the values for the a2/a4 and plot the ellipses directly? This may be back burner stuff for now but I think it would help. 

----- Original Message -----

**Comment by SmithJK** [comment]
Andrew, I understand plotting ellipses when one mixing ratio is fixed, but
how do you imagine that plot looking when both mixing ratios can vary?

**Comment by katieannemills** [comment]
k, couple points:
- I have the opposite confusion to @SmithJK's last point; with only one mixing ratio available to vary, we have functions a2(mixing ratio) or a4(mixing ratio); no ellipses there. I originally interpreted 'ellipses' as surfaces of constant a2 and a4, which is what the boundaries in the above image give you - but perhaps you meant something completely different, @AndrewMac1?
- for the pan, the limits are +-1 in mixing ratio since that was the limit of the sliders in the original version; I figured there was a reason for that. Is it physically meaningful to allow the user to select mixing ratios outside this range? If so, it's certainly possible.

**Comment by AndrewMac1** [comment]
If you have one mixing ratio and plot the a2 versus the a4 the plot gives an elliptical shape. I have attached an image for a 2->2->0 example called a2va4.png. If both mixing ratios can vary I am unsure what the plot will look like, maybe some figure eight shape I am not sure. I can make a plot and test it if you guys would like to see it, but this is something I have not encountered yet nor have I seen in literature.  

As for the mixing ratios they can definitely be larger then +/-1 I would suggest making the range on these to be something like +/-10. With that range you can see the convergence of the a2/a4 values which I am also attaching in the screen shot. I think it is better to have a wide range and then let the user zoom in to the area of interest that they prefer. I just figured out that the axes can be adjusted by zooming in and out or clicking on the graph and dragging, so the second portion of my previous email is now not needed.  

----- Original Message -----

**Comment by SmithJK** [comment]
If you do a parametric plot of (a2,a4) as a function of a single mixing
ratio, you get an ellipse. See attached image.

I originally set the limits in mixing ratio as +/-1 because +/- infinity
seemed too wide. To compensate, you are allowed to switch the order of the
angular momenta in the ratio. This allows us to cover the entire parameter
space while still having a limit on the mixing ratio.

**Comment by SmithJK** [comment]
We're slightly redundant today with the ellipse explanation... oops!

**Comment by katieannemills** [comment]
ah, ok - so we can stick with bounding mixing ratios at +-1 per @SmithJK's comment, but instead of the iso surfaces you actually wanted a parametric plot of a2 and a4 as a function of one mixing ratio - shouldn't be too big a deal, I'll see what I can do.

**Comment by katieannemills** [comment]
Alright, the latest push adds these parametric ellipses; also, I see what you mean @AndrewMac1 by the 'convergence of the a2/a4 values' now; to explore this, I also implemented the controls you ask for to allow the user to set the bounds of a2 and a4 computation, and the number of samples. Let me know if this is what you had in mind, and thanks for everyone's feedback!
